name: Smart Contract CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Build & Test Smart Contract
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.92.0
          targets: wasm32v1-none
          components: rustfmt

      - name: Install Stellar CLI
        uses: stellar/actions/stellar-cli@v1

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Build Smart Contract
        run: stellar contract build

      - name: Run Contract Tests
        run: cargo test --workspace
